// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uoducifrotxtnjvyozec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZHVjaWZyb3R4dG5qdnlvemVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0ODUxOTIsImV4cCI6MjA1MTA2MTE5Mn0.nrQY9y6Xg1ILtjtqvhLWrOFfA8LgGioAm8tchOOC9Tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);